title: Add a looping soundtrack
hero_image: images/banner.png
description: Add a looping soundtrack
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Add a looping soundtrack
