---
title: Ajouter une bande son en boucle
hero_image: images/banner.png
description: Ajouter une bande son en boucle
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Ajouter une bande son en boucle
